### ISSUE TITLE
proxy mode not working as documented

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#104]
When running pywb via uwsgi and proxy mode enabled in `config.yaml`:

```yaml
enable_http_proxy: true
proxy_options:
   use_default_coll: false
```

pywb should send a proxy auth header for collection selection, as described in the [wiki](https://github.com/ikreymer/pywb/wiki/Pywb-Proxy-Mode-Usage#proxy-auth-selection).

Instead, pywb offers to select a collection via the *Pywb Proxy Collection Selector* page. Clicking on a link does set a cookie like `__pywb_proxy_sesh=rv63uhi4` for the desired domain, but then returns to the *Proxy Collection Selector* at for instance http://select.pywb.proxy/http://www.vvork.com/

**Comment by ikreymer** [comment]
Looks like the wiki doc is a little out of date and needs updating.
The cookie based selection method is actually the default, instead of proxy auth, since the proxy auth requires user to know the collection name before hand. To use proxy auth, need to set `cookie_resolver: false`

```
enable_http_proxy: true
proxy_options:
   cookie_resolver: false
   use_default_coll: false
```
and it'll show the proxy auth dialog.

However, i think the cookie method should be used whenever possible. Unfortunately, waitress, now the default WSGI server, does not support proxy mode at all it turns out. When running in uwsgi, there is one more step that is needed, and that is to enable the shared cache in uWSGI:

`cache2 = name=sesh,items=500,blocksize=64,keysize=64`

This is part of the `pywb-proxy-demo` uwsgi.ini but perhaps should just be part of the default uwsgi.ini in pywb. This allows the session cookie data to be shared across multiple uWSGI workers.
