### ISSUE TITLE
Simplified Configuration System for multiple collections

### ISSUE THREAD

**Issue by ikreymer** [ikreymer/pywb#55]
Add an optional 'convention over configuration' system for setting up collections of warcs and cdx files..

Currently, setting up multiple collections can be a bit tedious. For example, configuring two collections, each with custom set of cdx, warcs, search page and banner might look like this:

```yaml
coll1:
        index_paths: ./coll1/cdx/
        archive_paths: ./coll1/warcs/
        banner_html: ./coll1/templates/banner.html
        search_html: ./coll1/templates/search.html

coll2:
        index_paths: ./coll1/cdx/
        archive_paths: ./coll1/warcs/
        banner_html: ./coll1/templates/banner.html
        search_html: ./coll1/templates/search.html
```

With the new convention system, the collections can instead be configured implicitly within a `collections` directory, eg: `collections/coll1/`, `collections/coll2`, and each having a
`indexes` , `archive` and an optional `templates` subdir.

Edit: changed `cdx` -> `indexes`, `warcs` -> `archive` in new config system
